version: '3.0'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
  db_admin:
    container_name: db
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
